use_frameworks!

platform :ios, '9.0'

target 'WQCameraControllerforSwift_Example' do
  pod 'WQCameraControllerforSwift', :path => '../'

  target 'WQCameraControllerforSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
